name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  date:  # id of input
    description: 'Event time'
    required: false
    default: ''
  graph-id:
    description: 'Name of the graph'
    required: true
  quantity:
    description: 'Value of the event' 
    required: false
    default: '1'
  username: 
    description: 'Username of the graph owner'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.username }}
    - ${{ inputs.graph }}
    - ${{ inputs.quantity }}
    - ${{ inputs.date }}
