name: 'pixela-action'
description: 'Post metrics to Pixela'
inputs:
  date: 
    description: 'Event time'
    required: false
    default: ''
  graph-id:
    description: 'Name of the graph'
    required: true
  quantity:
    description: 'Value of the event' 
    required: false
    default: '1'
  username: 
    description: 'Username of the graph owner'
    required: true
  token: 
    description: 'Credential to access the API'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.username }}
    - ${{ inputs.token }}
    - ${{ inputs.graph-id }}
    - ${{ inputs.quantity }}
    - ${{ inputs.date }}
branding:
  icon: 'git-commit'
  color: 'green'
