name: Test
on: pull_request

jobs:
  test-count-metric:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: With
        uses: ./
        with:
          graph-id: test-count
          username: ${{ secrets.PIXELA_USERNAME }}
          token: ${{ secrets.PIXELA_TOKEN }}
